config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :readers
  root 'books#available'

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_up: 'signup' }
  get 'logout', to: 'pages#logout', as: 'logout'

  resources :account, only: %i[index update]
  resources :books do
    member do
      post 'mark_as_available'
    end
  end
  resources :users

  # static pages
  pages = %w[
    privacy terms
  ]

  pages.each do |page|
    get "/#{page}", to: "pages##{page}", as: page.gsub('-', '_').to_s
  end

  post '/invite' => 'users#invite', as: 'invite'

  # admin panels
  authenticated :user, ->(user) { user.admin? } do
    namespace :admin do
      resources :dashboard, only: [:index]
      resources :impersonations, only: [:new]
      resources :users, only: %i[edit update destroy]
    end

    # convenience helper
  end
  get 'available_books', to: 'books#available'
end

app/models/book.rb
# frozen_string_literal: true

class Book < ApplicationRecord
  #      t.string :title
  #       t.string :author
  #       t.string :description
  #
  #       t.boolean :available, default: true
  #
  #       t.references :user, foreign_key: true, index: true, null: true
  #
  #       t.timestamps
  belongs_to :user, optional: true

  has_one_attached :cover_image, dependent: :destroy
end

app/controllers/books_controller.rb
# frozen_string_literal: true

class BooksController < ApplicationController
  before_action :set_book, only: %i[show edit update destroy mark_as_available]
  # before_action :authenticate_user!, only: %i[new create edit update destroy]

  # GET /books
  def index
    @books = Book.all.order(created_at: :asc)
  end

  def available
    @books = Book.all.order(created_at: :asc).where(available: true)
  end

  def mark_as_available
    @book.update(available: true, reader_id: nil)
    redirect_to available_books_path
  end

  # GET /books/slug
  def show; end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/slug/edit
  def edit; end

  # POST /books
  def create
    @book = Book.new(book_params)

    if @book.save
      redirect_to book_path(@book.id), notice: 'Livro foi criado.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /books/slug
  def update
    @book.title = book_params[:title]
    @book.author = book_params[:author]
    @book.description = book_params[:description]
    @book.reader_id = book_params[:reader_id]
    @book.cover_image.attach(book_params[:cover_image]) if book_params[:cover_image].present?
    @book.reader_id.present? ? @book.update(available: false) : @book.update(available: true)

    if @book.save
      redirect_to book_path(@book.id), notice: 'Livro foi atualizado com sucesso!.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /books/1
  def destroy
    @book.destroy
    redirect_to books_url, notice: 'Livro foi apagado.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_book
    @book = Book.find(params[:id])
  end

  # Only allow a list of trusted parameters through, but add :body, and use slug instead of id in the URL.
  def book_params
    params.require(:book).permit(:title, :author, :description, :cover_image, :reader_id)
  end
end

app/helpers/books_helper.rb
# frozen_string_literal: true

module BooksHelper
end

app/views/books/_book.html.erb
<%= link_to book_path(book),
            class: "group block w-full max-w-xs h-72 flex flex-col
                    bg-white border border-gray-200 rounded-lg overflow-hidden
                    shadow-sm hover:shadow-lg hover:-translate-y-1
                    transform transition duration-200" do %>

  <% if book.cover_image.attached? %>
    <div class="w-full h-48 bg-gray-100 overflow-hidden p-1 flex justify-center rounded-b-lg", style="height: 225px; padding-bottom: 0px">
      <%= image_tag book.cover_image,
                    alt: book.title,
                    class: "object-cover mx-auto " %>
    </div>
  <% else %>
    <div class="w-full h-44 bg-gray-100 flex items-center justify-center text-gray-400 rounded-b-lg">
      Sem capa
    </div>
  <% end %>

<div class="p-4 flex-1 flex flex-col">
    <h3 class="text-lg font-semibold text-gray-800 truncate mb-2">
      <%= book.title %>
    </h3>
    <p class="text-sm text-gray-600 mb-3 truncate">
      <%= book.author.present? ? "Autor: #{book.author}" : "Autor: não informado" %>
    </p>
    <p class="text-sm text-gray-500 flex-1 overflow-hidden">
      <%= truncate(book.description, length: 100) %>
    </p>
  </div>

  <footer class="px-4 py-2 bg-gray-50 text-center">
    <p class="text-xs text-gray-400 uppercase">
      Publicado em <%= l(book.created_at.to_date, format: :long) %>
    </p>
  </footer>

<% end %>

app/views/books/_form.html.erb
<%= form_with(model: @book) do |form| %>
  <% if @book.errors.any? %>
    <div class="bg-red-100 text-red-700 p-4 rounded mb-4">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% @book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="flex flex-col space-y-6">
    <% unless turbo_native_app? %>
    <% end %>
    <div class="bg-white border shadow pt-5 lg:rounded-lg">
      <div class="px-4">
        <div class="mt-5 md:mt-0 md:col-span-2">
          <div class="space-y-6">
            <div class="sm:col-span-3">
              <%= form.label :titulo, class: "block text-sm font-medium text-gray-700" %>
              <%= form.text_field :title, required: true, class: "mt-1 focus:border-primary-500 focus:ring focus:ring-primary-500 focus:ring-opacity-50 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md", placeholder: "Título do seu livro", maxlength: 65 %>
            </div>

            <div class="sm:col-span-3">
              <%= form.label :author, class: "block text-sm font-medium text-gray-700" %>
              <%= form.text_field :author,
                                  required: true,
                                  class: "mt-1 focus:border-primary-500 focus:ring focus:ring-primary-500 focus:ring-opacity-50 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md",
                                  placeholder: "Nome do autor" %>
            </div>

            <div class="sm:col-span-3">
              <%= form.label :descricao, class: "block text-sm font-medium text-gray-700" %>
              <%= form.text_area :description, required: true, rows: 2 , class: "mt-1 focus:border-primary-500 focus:ring focus:ring-primary-500 focus:ring-opacity-50 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md", placeholder: "Descreva seu livro aqui.", maxlength: 155 %>
            </div>

            <div class="col-span-full">
              <label for="cover_image" class="block text-sm font-medium leading-6 text-gray-900">Capa do livro</label>
              <div id="drop_zone" class="mt-2 flex justify-center rounded-lg border border-dashed border-gray-900/25 px-6 py-10">
                <div class="text-center">
                  <%= image_tag @book.cover_image, id: 'cover_image_preview', data: { url: url_for(@book.cover_image) } if @book.cover_image.attached? %>
                  <img id="cover_image_preview" src="#" alt="Cover Image Preview" class="hidden"/>
                  <div class="mt-4 flex text-sm leading-6 text-gray-600 justify-center">
                    <label for="cover_image" class="relative cursor-pointer rounded-md bg-white font-semibold text-gray-600 focus-within:outline-none focus-within:ring-2 focus-within:ring-gray-600 focus-within:ring-offset-2 hover:text-gray-500">
                      <%= form.file_field :cover_image, id: 'cover_image', class: 'sr-only', required: !@book.cover_image.attached? %>
                    </label>
                    <p class="pl-1">Arraste aqui :)</p>
                  </div>
                  <p class="text-xs leading-5 text-gray-600">PNG ou JPEG</p>
                </div>
              </div>
            </div>

            <div class="sm:col-span-3">
              <%= form.label :leitor, class: "block text-sm font-medium text-gray-700" %>
              <%= form.select :reader_id, Reader.all.map { |user| [user.name, user.id] }, { prompt: 'Selecionar leitor' }, {class: "mt-1 block w-full pl-3 pr-10 py-2 text-base border-gray-300 focus:outline-none sm:text-sm rounded-md" } %>
            </div>
          </div>
        </div>
      </div>
      <div class="flex justify-center items-center mt-4 sticky bottom-0 px-4 py-5 bg-gray-50 border-t rounded-b-lg">
        <%= form.submit @book.id.present? ? 'Atualizar' : 'Criar', class:"group relative w-full flex justify-center py-2.5 px-4 border border-transparent text-sm leading-5 font-medium rounded-md text-white bg-primary-600 hover:bg-primary-700 focus:outline-none cursor-pointer"%>
      </div>
    </div>
  </div>
<% end %>

<script>
  // Preview the cover image
  document.getElementById('cover_image').addEventListener('change', function(e) {
    var file = e.target.files[0];
    var reader = new FileReader();

    reader.onloadend = function() {
      document.getElementById('cover_image_preview').src = reader.result;
      document.getElementById('cover_image_preview').style.display = 'block';
    }

    if (file) {
      reader.readAsDataURL(file);
    } else {
      document.getElementById('cover_image_preview').src = "";
    }
  });

  document.addEventListener('DOMContentLoaded', function() {
  var coverImagePreview = document.getElementById('cover_image_preview');
  if (coverImagePreview) {
    coverImagePreview.src = coverImagePreview.dataset.url;
    coverImagePreview.style.display = 'opacity-100';
  }
  });

  var dropZone = document.getElementById('drop_zone');
  var fileInput = document.getElementById('cover_image');

  dropZone.addEventListener('dragover', function(e) {
  e.preventDefault();
  dropZone.classList.add('bg-gray-100');
  });

  dropZone.addEventListener('dragleave', function(e) {
  e.preventDefault();
  dropZone.classList.remove('bg-gray-100');
  });

  dropZone.addEventListener('drop', function(e) {
  e.preventDefault();
  dropZone.classList.remove('bg-gray-100');

  var files = e.dataTransfer.files;
  if (files.length > 0) {
    fileInput.files = files;
    // Trigger the 'change' event to update the preview
    var event = new Event('change');
    fileInput.dispatchEvent(event);
  }
  });
</script>

app/views/books/artigos.html.erb
<% meta title: "Artigos", description: "Meus artigos" %>

<%# Title %>
<div class="mt-16 mx-auto max-w-3xl px-4 sm:mt-24">
  <div class="text-center">
    <h1 class="text-2xl tracking-tight font-extrabold sm:text-3xl md:text-4xl font-display text-gray-800">
      <span class="block">Artigos</span>
    </h1>
  </div>
</div>

<% if current_user.present? %>
  <%# New blog post button, only accessibly by admins %>
  <div class="mt-8 mx-auto max-w-fit">
    <div class="group relative w-full flex justify-center py-2.5 px-4 border border-transparent text-sm leading-5 font-medium rounded-md text-white bg-primary-600 hover:bg-primary-700 focus:outline-none">
      <div class="text-base flex justify-center items-center">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 -ml-1 mr-2" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
          <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm1-11a1 1 0 10-2 0v2H7a1 1 0 100 2h2v2a1 1 0 102 0v-2h2a1 1 0 100-2h-2V7z" clip-rule="evenodd"></path>
        </svg>
        <%= link_to '/blog/new', class: "focus:outline-none" do %>
          <span class="absolute inset-0" aria-hidden="true"></span>
          Criar novo artigo
        <% end %>
      </div>
    </div>
  </div>
<% end %>

<div class="font-inter antialiased text-gray-800 tracking-tight my-16">
  <main class="grow">
    <section>
      <div class="mx-auto max-w-7xl px-6 lg:px-8">
        <div class="mx-auto mt-16 grid max-w-2xl grid-cols-1 gap-x-8 gap-y-20 lg:mx-0 lg:max-w-none lg:grid-cols-3">
          <%# Blog post list %>
          <% @blog_posts.each do |blog_post| %>
            <%= render blog_post %>
          <% end %>
        </div>
      </div>
    </section>
  </main>

</div>

app/views/books/available.html.erb
<% meta title: "Livros Disponveis", description: "Livros disponiveis" %>

<div class="mt-16 mx-auto max-w-3xl px-4 sm:mt-24">
  <div class="text-center">
    <h1 class="text-2xl tracking-tight font-extrabold sm:text-3xl md:text-4xl font-display text-gray-800">
      <span class="block">Livros disponiveis</span>
    </h1>
  </div>
</div>

<div class="font-inter antialiased text-gray-800 tracking-tight my-16">
  <main class="grow">
    <section>
      <div class="mx-auto max-w-7xl px-6 lg:px-8">
        <div
          class="grid
                 grid-cols-1        <!-- 1 coluna por padrão -->
                 sm:grid-cols-2     <!-- ≥640px: 2 colunas -->
                 md:grid-cols-3     <!-- ≥768px: 3 colunas -->
                 lg:grid-cols-4     <!-- ≥1024px: 4 colunas -->
                 gap-x-8 gap-y-20
                 mx-auto lg:mx-0">
          <% @books.each do |book| %>
            <%= render book %>
          <% end %>
        </div>
      </div>
    </section>
  </main>

</div>

app/views/books/edit.html.erb
<% meta title: "Editar", description: "" %>

<h1 class="text-xl text-center font-bold leading-tight text-gray-900 mx-4 lg:mx-0 mt-8 lg:mt-16">Editar livro</h1>

<div class="flex justify-center flex-col space-y-3 mt-4 text-center">
  <%= link_to "Voltar", books_path, class:"mx-auto w-fit shrink-0 mt-4 md:mt-0 inline-flex items-center justify-center sm:justify-start px-4 py-2 border border-gray-300 shadow-sm text-base font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary-500" %>
</div>

<div class="max-w-2xl mx-auto mt-8">
  <%= render "form", blog_post: @book %>
</div>

app/views/books/index.html.erb
<% meta title: "Livros", description: "Todos os lviros" %>


<div class="mt-16 mx-auto max-w-3xl px-4 sm:mt-24">
  <div class="text-center">
    <h1 class="text-2xl tracking-tight font-extrabold sm:text-3xl md:text-4xl font-display text-gray-800">
      <span class="block">Livros</span>
    </h1>
  </div>
</div>

<div class="font-inter antialiased text-gray-800 tracking-tight my-16">
  <main class="grow">
    <section>
      <div class="mx-auto max-w-7xl px-6 lg:px-8">
        <div class="flex justify-end mb-6 w-full">
          <%= link_to "Novo Livro", new_book_path,
                      class: "px-4 py-2 bg-primary-600 text-white rounded-md hover:bg-primary-700" %>
        </div>
        <div
          class="grid
                 grid-cols-1        <!-- 1 coluna por padrão -->
                 sm:grid-cols-2     <!-- ≥640px: 2 colunas -->
                 md:grid-cols-3     <!-- ≥768px: 3 colunas -->
                 lg:grid-cols-4     <!-- ≥1024px: 4 colunas -->
                 gap-x-8 gap-y-20
                 mx-auto lg:mx-0">
          <% @books.each do |book| %>
            <%= render book %>
          <% end %>
        </div>
      </div>
    </section>
  </main>
</div>

app/views/books/new.html.erb
<% meta title: "Create a new blog post", description: "New blog post for #{ENV['COMPANY_NAME']}." %>

<h1 class="text-xl text-center font-bold leading-tight text-gray-900 mx-4 lg:mx-0 mt-8 lg:mt-16">Novo livros</h1>

<div class="flex justify-center flex-col space-y-3 mt-4 text-center">
  <%= link_to "Voltar para livros", books_path, class:"mx-auto w-fit shrink-0 mt-4 md:mt-0 inline-flex items-center justify-center sm:justify-start px-4 py-2 border border-gray-300 shadow-sm text-base font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary-500" %>
</div>

<div class="max-w-2xl mx-auto mt-8">
  <%= render "form", book: @book %>
</div>

app/views/books/review.html.erb
<% meta title: "Artigos", description: "Meus artigos" %>

<%# Title %>
<div class="mt-16 mx-auto max-w-3xl px-4 sm:mt-24">
  <div class="text-center">
    <h1 class="text-2xl tracking-tight font-extrabold sm:text-3xl md:text-4xl font-display text-gray-800">
      <span class="block">Avaliar</span>
    </h1>
  </div>
</div>

<div class="font-inter antialiased text-gray-800 tracking-tight my-16">
  <main class="grow">
    <section>
      <div class="mx-auto max-w-7xl px-6 lg:px-8">
        <div class="mx-auto mt-16 grid max-w-2xl grid-cols-1 gap-x-8 gap-y-20 lg:mx-0 lg:max-w-none lg:grid-cols-3">
          <%# Blog post list %>
          <% @blog_posts.each do |blog_post| %>
            <%= render blog_post %>
          <% end %>
        </div>
      </div>
    </section>
  </main>

</div>

app/views/books/show.html.erb
<% meta title: @book.title, description: @book.description %>

<div class="font-inter antialiased text-gray-800 tracking-tight my-16">
  <main class="grow">
    <section>
      <div class="mx-auto max-w-2xl px-4 lg:px-8 border p-4 rounded-lg">
        <%= link_to "← Voltar para todos os livros", books_path, class:"hover:opacity-75 mr-1 w-fit font-semibold" %>
        <article class="flex flex-col items-start justify-between mt-4">
          <div class="relative w-full">
            <%= image_tag @book.cover_image, class:"aspect-[9/16] w-full h-full rounded-2xl bg-gray-100 object-cover" if @book.cover_image.attached? %>
            <div class="absolute inset-0 rounded-2xl ring-1 ring-inset ring-gray-900/10"></div>
          </div>
          <% if current_user.present? %>
            <div class="mx-auto mt-4">
              <div class="flex space-x-2 my-2 mx-auto justify-center items-center">
                <%= link_to edit_book_path(@book.id), class:"shrink-0 mt-4 md:mt-0 inline-flex items-center justify-center px-4 py-2 border border-gray-300 shadow-sm text-base font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary-500" do %>
                  <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 -ml-1 mr-3" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                    <path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z"></path>
                  </svg>
                  Editar
                <% end %>
                <%= button_to @book, method: :delete, class:"shrink-0 mt-4 md:mt-0 inline-flex items-center justify-center px-4 py-2 border border-gray-300 shadow-sm text-base font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary-500" do %> <!-- Delete button -->
                  <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 -ml-1 mr-3" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
                    <path fill-rule="evenodd" d="M16.5 4.478v.227a48.816 48.816 0 013.878.512.75.75 0 11-.256 1.478l-.209-.035-1.005 13.07a3 3 0 01-2.991 2.77H8.084a3 3 0 01-2.991-2.77L4.087 6.66l-.209.035a.75.75 0 01-.256-1.478A48.567 48.567 0 017.5 4.705v-.227c0-1.564 1.213-2.9 2.816-2.951a52.662 52.662 0 013.369 0c1.603.051 2.815 1.387 2.815 2.951zm-6.136-1.452a51.196 51.196 0 013.273 0C14.39 3.05 15 3.684 15 4.478v.113a49.488 49.488 0 00-6 0v-.113c0-.794.609-1.428 1.364-1.452zm-.355 5.945a.75.75 0 10-1.5.058l.347 9a.75.75 0 101.499-.058l-.346-9zm5.48.058a.75.75 0 10-1.498-.058l-.347 9a.75.75 0 001.5.058l.345-9z" clip-rule="evenodd"></path>
                  </svg>
                  Deletar
                <% end %>

                <% if @book.reader_id %>
                <%= button_to mark_as_available_book_path(@book), method: :post, title:"Marque como disponível", class:"shrink-0 mt-4 md:mt-0 inline-flex items-center justify-center px-4 py-2 border border-gray-300 shadow-sm text-base font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary-500" do %>
                  <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 -ml-1 mr-3 text-gray-500" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7" />
                  </svg>
                  Disponível
                <% end %>
                  <%end %>
              </div>
            </div>
          <% end %>
          <div class="w-full prose prose-lg">
            <div class="group relative">
              <% if @book.reader_id.present? %>
              <p class="text-base text-center md:text-lg">Alugado por: <%= Reader.find(@book.reader_id).name %></p>
                <%end  %>
              <div class="text-xs mx-auto text-center w-full mb-6 mt-12">
                 <time class="relative z-10 rounded-full bg-white px-3 py-1.5 font-medium text-gray-600 border" datetime="<%= @book.updated_at.strftime('%m-%d-%Y') %>" class="text-gray-500"><%= @book.created_at.strftime('%B %d, %Y') %></time>
              </div>
              <h1 class=" text-xl sm:text-2xl md:text-3xl lg:text-4xl font-bold leading-6 text-gray-900 text-center mb-8">
                <%= @book.title %>
              </h1>
              <p class="text-base md:text-lg">  Autor: <%= @book.author.present? ? @book.author : "Não informado" %></p>
              <p class="text-base md:text-lg"><%= @book.description %></p>
            </div>
          </article>
        </div>
      </section>
    </main>
  </div>